console.log("Exception Handling Started ................");


try{
    console.log(a);
}
catch(E ){
    console.log("Something went wrong");
}